DROP TRIGGER IF EXISTS TR_episodeWatched ON EpisodesWatched;
DROP FUNCTION IF EXISTS episodeWatched();
DROP TRIGGER IF EXISTS TR_episodeNotWatched ON EpisodesWatched;
DROP FUNCTION IF EXISTS episodeNotWatched();
DROP TRIGGER IF EXISTS TR_seasonWatched ON SeasonsWatched;
DROP FUNCTION IF EXISTS seasonWatched();
DROP TRIGGER IF EXISTS TR_supprUser ON Users;
DROP FUNCTION IF EXISTS supprUser();

DROP TABLE IF EXISTS SeriesWatched;
DROP TABLE IF EXISTS SeasonsWatched;
DROP TABLE IF EXISTS EpisodesWatched;
DROP TABLE IF EXISTS Watch;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Episodes;
DROP TABLE IF EXISTS Seasons;
DROP TABLE IF EXISTS Series;

DROP TYPE IF EXISTS t_status;