DROP TABLE IF EXISTS Watched;
DROP TABLE IF EXISTS Watch;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Episodes;
DROP TABLE IF EXISTS Seasons;
DROP TABLE IF EXISTS Series;

DROP TYPE IF EXISTS t_status;